# workflow name
name: Pull Request

# on events
on:
  # run on each pull request
  pull_request:
    types: [ synchronize, opened ]
    branches:
      - main
      - ci-test # testing branch for github action
  push:
    branches:
      - main

# workflow tasks
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Compile 
        run: make
      - name: Test
        run: make test
